#!/bin/bash

URACER_DESKTOP="`pwd`/uracer-desktop"
URACER_VERSIONINFO="${URACER_DESKTOP}/src/com/bitfire/uracer/VersionInfo.java"
#USERVE_VERSIONINFO="/home/manuel/dev/python/userve/uracer_version.py"

BUILD_NAME="$(git describe --long | tr -d \"\n\")"
#BUILD_BRANCH="$(git name-rev --name-only HEAD)"
BUILD_BRANCH="$(basename $(git symbolic-ref HEAD 2>/dev/null))"
BUILD_CODE="${BUILD_NAME}/${BUILD_BRANCH}"
BUILD_ID="$(cat .git/$(git symbolic-ref HEAD 2>/dev/null)|tr -d '\n')"



cat <<EOF > $URACER_VERSIONINFO

package com.bitfire.uracer;

// MACHINE-GENERATED CODE, DO NOT TOUCH!
//
// Contains the latest uracer version
public final class VersionInfo {
	public static final String versionName = "$BUILD_CODE";

	private VersionInfo () {
	}
}

EOF


#cat <<EOF > $USERVE_VERSIONINFO
#!/usr/bin/env python2
 #coding=utf-8

 #MACHINE-GENERATED CODE, DO NOT TOUCH!

 #Contains the latest uracer version
#uracer_version = "$BUILD_CODE"
#uracer_build_name = "$BUILD_NAME"
#uracer_build_branch = "$BUILD_BRANCH"
#uracer_build_id = "$BUILD_ID"
#EOF



#URACER_ANDROID="`pwd`/uracer-android"
#MANIFEST="${URACER_ANDROID}/AndroidManifest.xml"
#POM="${URACER_DESKTOP}/pom.xml"

#if [ ! -e "${MANIFEST}" ] ;
#then
	#echo "Cannot update version information, AndroidManifest.xml not found."
	#exit 1
#fi

#if [ ! -e "${VERINFO}" ] ;
#then
	#echo "Cannot update version information, VersionInfo.java not found."
	#exit 1
#fi

# increment android:versionCode in manifest
#perl -npi -e 's/^(.*android:versionCode=")(\d+)(".*)$/"$1" . ($2+1) . "$3"/e;' ${MANIFEST}

# update android:versionName in manifest
#perl -npi -e 's/^(.*android:versionName=")(.+)(".*)$/"$1" . "'${BUILD_CODE}'" . "$3"/e;' ${MANIFEST}

# update uracer class file
#perl -npi -e 's/^(.*public static final String versionName = ")(.+)(".*)$/"$1" . "'${BUILD_CODE}'" . "$3"/e;' ${VERINFO}

# update pom.xml
#perl -npi -e 's/^(\s\s<version>)(.+)(<\/version>)$/"$1" . "'${BUILD_NAME}'" . "$3"/e;' ${POM}
